### ISSUE TITLE
Add help to creation form how to define license

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-UI#225]
When I upload an Rmd file with incorrect license definitions, I should get a helpful hint how to define the license correctly:

![image](https://user-images.githubusercontent.com/1325054/123404936-a4712580-d5a9-11eb-923f-20472d1d1b7d.png)

Incorrect:

```yaml
license:
  code: Apache License 2.0
  data: Creative Commons Attribution Share-Alike 4.0
  text: CC BY 4.0
```

Correct:

```yaml
licenses:
  code: Apache-2.0
  data: CC-BY-SA-4.0
  text: CC-BY-4.0
```

Maybe a link to https://spdx.org/licenses/ in the warning?

Can users use both the identifier or the full name?
